// <auto-generated />
using System;
using MVC_projekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_projekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507141524_AddUserPasswordHash")]
    partial class AddUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_projekt.Models.Duration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Base")
                        .HasColumnType("int");

                    b.Property<bool>("IsDotted")
                        .HasColumnType("bit");

                    b.Property<int>("TabColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabColumnId")
                        .IsUnique();

                    b.ToTable("Durations");
                });

            modelBuilder.Entity("MVC_projekt.Models.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BPM")
                        .HasColumnType("int");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("StringTuning")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("TabMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabMeasureId");

                    b.ToTable("TabColumns");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasureNumber")
                        .HasColumnType("int");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSignatureBottom")
                        .HasColumnType("int");

                    b.Property<int>("TimeSignatureTop")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabId");

                    b.ToTable("TabMeasures");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bend")
                        .HasColumnType("bit");

                    b.Property<int>("Fret")
                        .HasColumnType("int");

                    b.Property<bool>("HammerOn")
                        .HasColumnType("bit");

                    b.Property<bool>("PalmMuted")
                        .HasColumnType("bit");

                    b.Property<bool>("PullOff")
                        .HasColumnType("bit");

                    b.Property<int>("StringNumber")
                        .HasColumnType("int");

                    b.Property<int>("TabColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabColumnId");

                    b.ToTable("TabNotes");
                });

            modelBuilder.Entity("MVC_projekt.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_projekt.Models.Duration", b =>
                {
                    b.HasOne("MVC_projekt.Models.TabColumn", "TabColumn")
                        .WithOne("ColumnDuration")
                        .HasForeignKey("MVC_projekt.Models.Duration", "TabColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabColumn");
                });

            modelBuilder.Entity("MVC_projekt.Models.Tab", b =>
                {
                    b.HasOne("MVC_projekt.Models.User", "Creator")
                        .WithMany("Tabs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabColumn", b =>
                {
                    b.HasOne("MVC_projekt.Models.TabMeasure", "TabMeasure")
                        .WithMany("Columns")
                        .HasForeignKey("TabMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabMeasure");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabMeasure", b =>
                {
                    b.HasOne("MVC_projekt.Models.Tab", "Tab")
                        .WithMany("Measures")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabNote", b =>
                {
                    b.HasOne("MVC_projekt.Models.TabColumn", "TabColumn")
                        .WithMany("Notes")
                        .HasForeignKey("TabColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabColumn");
                });

            modelBuilder.Entity("MVC_projekt.Models.Tab", b =>
                {
                    b.Navigation("Measures");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabColumn", b =>
                {
                    b.Navigation("ColumnDuration")
                        .IsRequired();

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MVC_projekt.Models.TabMeasure", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("MVC_projekt.Models.User", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
